#!/bin/bash

RES_DIR=results-N-n-const

date +%X
./wave-eq-cuda gpu11 14 4 3
date +%X
./wave-eq-cuda gpu11 15 5 3
date +%X
./wave-eq-cuda gpu11 16 6 3
date +%X
./wave-eq-cuda gpu11 17 7 3
date +%X
./wave-eq-cuda gpu11 18 8 3
date +%X
./wave-eq-cuda gpu11 19 9 3
date +%X
./wave-eq-cuda gpu11 20 10 3
date +%X
./wave-eq-cuda gpu11 21 11 3
date +%X
./wave-eq-cuda gpu11 22 12 3
date +%X
./wave-eq-cuda gpu11 23 13 3
date +%X

#mkdir $RES_DIR
mv *.txt $RES_DIR/.
